batch_size: 16
cond_disc: false
data_path: "/home/allenhung/nas189/home/one_bar_loop_all"  # Converted path to a string
downsamp_factor: 4
epochs: 30000
lambda_feat: 10
load_path: null
log_interval: 100
n_layers_D: 4
n_mel_channels: 80
n_residual_layers: 3
n_test_samples: 8
ndf: 16
ngf: 32
num_D: 3
save_interval: 1000
save_path: "logs/one_bar_all"  # Converted path to a string
seq_len: 8192
